/**
 * Invariants for the committed card catalogs.
 *
 * The unit tests cover the code that READS this data; this checks the data
 * itself, which is generated by a long pipeline (scrape -> OCR -> vision ->
 * triangulate) and has silently regressed before. The zero-rung check exists
 * because a ladder missing its bottom rung made every power stage read one
 * rung high, and that reached the board before anyone noticed.
 *
 *   node scripts/check-data.mjs
 */
import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dataDir = join(root, 'data');

const problems = [];
const notes = [];
const fail = (msg) => problems.push(msg);
const note = (msg) => notes.push(msg);

function readJson(name) {
  const path = join(dataDir, name);
  if (!existsSync(path)) return undefined;
  return JSON.parse(readFileSync(path, 'utf8'));
}

/* ---------- catalogs ---------- */

const catalogs = readdirSync(dataDir).filter((f) => f.startsWith('cards.') && f.endsWith('.enriched.json'));
if (catalogs.length === 0) fail('no cards.*.enriched.json committed — the server cannot start');

let personalities = 0;
let zeroRungBad = 0;
let ladderTooShort = 0;

for (const file of catalogs) {
  const cards = readJson(file);
  if (!Array.isArray(cards)) {
    fail(`${file} is not an array`);
    continue;
  }
  const ids = new Set();
  for (const c of cards) {
    if (!c?.id) fail(`${file}: a card has no id`);
    else if (ids.has(c.id)) fail(`${file}: duplicate card id ${c.id}`);
    ids.add(c?.id);

    const p = c?.rules?.personality;
    if (!p) continue;
    personalities++;
    const ladder = p.powerRatings;
    if (!Array.isArray(ladder) || ladder.length === 0) continue;

    // A scouter's bottom rung is printed 0/00/0000 — stage 0 must be 0.
    if (ladder.length >= 6 && ladder[0] !== 0) {
      zeroRungBad++;
      if (zeroRungBad <= 3) fail(`${file}: ${c.name} ladder starts at ${ladder[0]}, not 0`);
    }
    if (ladder.length > 0 && ladder.length < 6) ladderTooShort++;

    // Numeric rungs must strictly increase; 'Z' sits outside the ordering.
    const nums = ladder.filter((r) => typeof r === 'number');
    for (let i = 1; i < nums.length; i++) {
      if (nums[i] <= nums[i - 1]) {
        fail(`${file}: ${c.name} ladder is not strictly increasing (${nums[i - 1]} -> ${nums[i]})`);
        break;
      }
    }
  }
  note(`${file}: ${cards.length} cards`);
}
note(`${personalities} personalities; ${ladderTooShort} with a short ladder (flagged, not fatal)`);

/* ---------- Physical Attack Table ---------- */

const pat = readJson('pat.json');
if (!pat) fail('data/pat.json missing — combat would fall back to the placeholder grid');
else {
  if (pat.placeholder === true) fail('data/pat.json is flagged placeholder:true');
  if (!Array.isArray(pat.brackets) || pat.brackets.length === 0) fail('pat.json has no brackets');
  else {
    if (!pat.brackets.some((b) => b.letter === 'D')) fail("pat.json has no 'D' bracket (needed by the go-first rule)");
    if (!Array.isArray(pat.damage) || pat.damage.length !== pat.brackets.length) {
      fail(`pat.json damage has ${pat.damage?.length} rows for ${pat.brackets.length} brackets`);
    } else {
      for (const [i, row] of pat.damage.entries()) {
        if (!Array.isArray(row) || row.length !== pat.brackets.length) {
          fail(`pat.json damage row ${i} is the wrong width`);
          break;
        }
      }
      if (pat.damage[0]?.[0] !== 1) fail('pat.json: A vs A must deal 1');
    }
    // Ranges must be contiguous so every rating maps to exactly one bracket.
    for (let i = 1; i < pat.brackets.length; i++) {
      const prev = pat.brackets[i - 1];
      const cur = pat.brackets[i];
      if (cur.minRating !== prev.maxRating + 1) {
        fail(`pat.json brackets ${prev.letter}->${cur.letter} are not contiguous`);
        break;
      }
    }
  }
  note(`pat.json: ${pat.brackets?.length} brackets`);
}

/* ---------- historical PAT transcriptions ---------- */

const patDir = join(dataDir, 'pat');
if (existsSync(patDir)) {
  const files = readdirSync(patDir).filter((f) => f.endsWith('.json'));
  for (const f of files) {
    const t = JSON.parse(readFileSync(join(patDir, f), 'utf8'));
    if (t.placeholder === true) fail(`data/pat/${f} is a placeholder`);
    if (t.damage?.[0]?.[0] !== 1) fail(`data/pat/${f}: A vs A must deal 1`);
  }
  note(`data/pat/: ${files.length} historical printings`);
}

/* ---------- report ---------- */

for (const n of notes) console.log(`  ${n}`);
if (zeroRungBad > 3) console.log(`  ...and ${zeroRungBad - 3} more zero-rung problems`);

if (problems.length) {
  console.error(`\n${problems.length} data problem(s):`);
  for (const p of problems.slice(0, 20)) console.error(`  ✖ ${p}`);
  process.exit(1);
}
console.log('\nAll card data invariants hold.');
